[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/goombaio/dag"
  version = "0.0.14"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  name = "github.com/apex/log"
  version = "1.1.0"
