version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: dep ensure
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Test
          command: ./cover-test.sh
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
        filters:
          branches:
            only: master